version: '2'
services:

  site_c:
    image: nginx:1.13.0-alpine
    container_name: site_c
    ports:
      - "8082:80"
    volumes:
      - ./test-app/dist/test-app/:/var/www/html/website
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  site_d:
    image: nginx:1.13.0-alpine
    container_name: site_d
    ports:
      - "8083:80"
    volumes:
      - ./test-app/dist/test-app/:/var/www/html/website
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  docker_proxy:
    image: nginx
    container_name: docker_proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
